require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MemberCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # MemberCompany. As you add validations to MemberCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => 'Test Company',
      :code => 'TEST'}
  end

  describe "GET index" do
    it "assigns all member_companies as @member_companies" do
      member_company = MemberCompany.create! valid_attributes
      get :index
      assigns(:member_companies).should eq([member_company])
    end
  end

  describe "GET show" do
    it "assigns the requested member_company as @member_company" do
      member_company = MemberCompany.create! valid_attributes
      get :show, :id => member_company.id.to_s
      assigns(:member_company).should eq(member_company)
    end
  end

  describe "GET new" do
    it "assigns a new member_company as @member_company" do
      get :new
      assigns(:member_company).should be_a_new(MemberCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested member_company as @member_company" do
      member_company = MemberCompany.create! valid_attributes
      get :edit, :id => member_company.id.to_s
      assigns(:member_company).should eq(member_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MemberCompany" do
        expect {
          post :create, :member_company => valid_attributes
        }.to change(MemberCompany, :count).by(1)
      end

      it "assigns a newly created member_company as @member_company" do
        post :create, :member_company => valid_attributes
        assigns(:member_company).should be_a(MemberCompany)
        assigns(:member_company).should be_persisted
      end

      it "redirects to the created member_company" do
        post :create, :member_company => valid_attributes
        response.should redirect_to(MemberCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved member_company as @member_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        MemberCompany.any_instance.stub(:save).and_return(false)
        post :create, :member_company => {}
        assigns(:member_company).should be_a_new(MemberCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MemberCompany.any_instance.stub(:save).and_return(false)
        post :create, :member_company => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested member_company" do
        member_company = MemberCompany.create! valid_attributes
        # Assuming there are no other member_companies in the database, this
        # specifies that the MemberCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MemberCompany.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => member_company.id, :member_company => {'these' => 'params'}
      end

      it "assigns the requested member_company as @member_company" do
        member_company = MemberCompany.create! valid_attributes
        put :update, :id => member_company.id, :member_company => valid_attributes
        assigns(:member_company).should eq(member_company)
      end

      it "redirects to the member_company" do
        member_company = MemberCompany.create! valid_attributes
        put :update, :id => member_company.id, :member_company => valid_attributes
        response.should redirect_to(member_company)
      end
    end

    describe "with invalid params" do
      it "assigns the member_company as @member_company" do
        member_company = MemberCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MemberCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => member_company.id.to_s, :member_company => {}
        assigns(:member_company).should eq(member_company)
      end

      it "re-renders the 'edit' template" do
        member_company = MemberCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MemberCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => member_company.id.to_s, :member_company => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested member_company" do
      member_company = MemberCompany.create! valid_attributes
      expect {
        delete :destroy, :id => member_company.id.to_s
      }.to change(MemberCompany, :count).by(-1)
    end

    it "redirects to the member_companies list" do
      member_company = MemberCompany.create! valid_attributes
      delete :destroy, :id => member_company.id.to_s
      response.should redirect_to(member_companies_url)
    end
  end

end
